name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "node scripts/ensure-env.cjs && npx prisma generate"
dev = "npx prisma migrate deploy && npx remix vite:dev"
