#!/usr/bin/env bash
# Creates a private copy (custom distribution) of the app for one store.
#   scripts/new-instance.sh <name> <client_id> "<app title>"
#   e.g. scripts/new-instance.sh temptico 1a2b3c... "Enigma Play - Temptico"
# Writes shopify.app.<name>.toml and adds <name> to instances.txt. Deploy it with
# Actions → "Deploy instance". The public app (shopify.app.toml) is not touched.
set -euo pipefail
name="${1:-}"; client_id="${2:-}"; title="${3:-}"
if [[ ! "$name" =~ ^[a-z0-9]{2,20}$ ]] || [ -z "$client_id" ] || [ -z "$title" ]; then
  echo "usage: $0 <name: a-z0-9> <client_id> \"<app title, max 30 chars>\"" >&2; exit 1
fi
[ "${#title}" -le 30 ] || { echo "app title must be at most 30 characters" >&2; exit 1; }
cd "$(dirname "$0")/.."
out="shopify.app.$name.toml"
python3 - "$name" "$client_id" "$title" "$out" <<'PY'
import re, sys
name, client_id, title, out = sys.argv[1:]
s = open("shopify.app.toml").read()
s = re.sub(r'^client_id = ".*"$', f'client_id = "{client_id}"', s, count=1, flags=re.M)
s = re.sub(r'^name = ".*"$', f'name = "{title}"', s, count=1, flags=re.M)
# Custom-distribution apps: no Billing API and no GDPR compliance topics
# (the install fails with them), so drop those webhook subscriptions.
# A subscription block is its header line plus the lines up to the next blank line.
s = re.sub(r'^  \[\[webhooks\.subscriptions\]\]\n(?:[^\n]+\n)*?[^\n]*(?:compliance_topics|app_subscriptions/update)[^\n]*\n(?:[^\n]+\n)*\n?',
           '', s, flags=re.M)
header = (f"# Private copy of the app for one store (instance \"{name}\").\n"
          "# Generated by scripts/new-instance.sh from shopify.app.toml; deployed by\n"
          "# .github/workflows/deploy-instance.yml, which fills in the fly.dev URLs.\n")
open(out, "w").write(header + s)
PY
touch instances.txt
grep -qx "$name" instances.txt || echo "$name" >> instances.txt
echo "Created $out. Next: add GitHub secrets SHOPIFY_API_SECRET_${name^^} and SHOPIFY_APP_AUTOMATION_TOKEN_${name^^}, then run Actions → Deploy instance → $name."
